name: First GitHub Action  

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    env:  # Define an environment variable at the job level
      GREETING: "Hello from GitHub Actions!"
    
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Print a message  
        run: echo "Hello, GitHub Actions!"  

      - name: Show current date  
        run: date  

      - name: Print a job-level environment variable  
        run: echo "$GREETING"  # Using job-level environment variable  

      - name: Print a step-level environment variable  
        env:
          CUSTOM_MESSAGE: "Step-level environment variable"
        run: echo "$CUSTOM_MESSAGE"  # Using step-level environment variable
