name: First GitHub Action  

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    env:  # Define environment variables at the job level
      GREETING: "Hello from GitHub Actions!"
    
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Print a message  
        run: echo "Hello, GitHub Actions!"  

      - name: Show current date  
        run: date  

      - name: Print an environment variable  
        run: echo "$GREETING"  # Use the environment variable
